default_stages: [commit, push]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://gitlab.com/pycqa/flake8
  rev: '3.7.9'  # pick a git hash / tag to point to
  hooks:
  - id: flake8

- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.8
