version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: floodfire
      MYSQL_USER: newsdiff
      MYSQL_PASSWORD: floodfire
      MYSQL_DATABASE: floodfire_newsdiff
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
